import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Header(){
  return (
    <header className="w-full border-b p-4 flex justify-between items-center">
      <Link href="/" className="font-bold">Home</Link>
      <nav className="space-x-4">
        <Link href="/about" className="hover:underline"> About</Link>
        <Link href="/Mountains" className="hover:underline">Mountains</Link>
        <Link href="/contact" className="hover:underline">Contact</Link>
        <Link href="/hotel" className="hover:underline">5 Stars Hotel</Link>
        <Link href="/registration" className="hover:underline">Register Now</Link>
      </nav>
    </header>
  )
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Header/>
        {children}
      </body>
    </html>
  );
}
